mysite/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'



urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/cart/models.py
from django.db import models

# Create your models here.

mysite/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]



class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

mysite/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

mysite/cart/templates/cart/detail.html
{% load static %}


<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>Infinity</title>
	<meta charset="UTF-8">
	<meta name="description" content=" Divisima | eCommerce Template">
	<meta name="keywords" content="divisima, eCommerce, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link type="image/x-icon" href="{% static 'shop/images/favicon.ico' %}" rel="shortcut icon"/>


	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet"/>


	<!-- Stylesheets -->
	<link type="text/css" href="{% static 'shop/css/bootstrap.min.css' %}"/>
	<link type="text/css" href="{% static 'shop/css/font-awesome.min.css' %}" rel="stylesheet"/>
	<link type="text/css" href="{% static 'shop/css/flaticon.css' %}" rel="stylesheet"/>
	<link type="text/css" href="{% static 'shop/css/slicknav.min.css' %}" rel="stylesheet"/>
	<link type="text/css" href="{% static 'shop/css/jquery-ui.min.css' %}" rel="stylesheet"/>
	<link type="text/css" href="{% static 'shop/css/owl.carousel.min.css' %}" rel="stylesheet"/>
	<link type="text/css" href="{% static 'shop/css/animate.css' %}"  rel="stylesheet"/>
	<link type="text/css" href="{% static 'shop/css/style.css' %}" rel="stylesheet"/>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
		<header class="header-section">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 text-center text-lg-left">
						<!-- logo -->
						<a href="{% url 'index' %}" class="site-logo">
							<img src="{% static 'shop/images/logo.png' %}" alt="">
						</a>
					</div>
					<div class="col-xl-6 col-lg-5">
						<form class="header-search-form" action="{% url 'search_results' %}", method="get">
							<input name="q" type="text" placeholder="Search on infinity ....">
							<button><i class="flaticon-search"></i></button>
						</form>
					</div>
					<div class="col-xl-4 col-lg-5">
						<div class="user-panel">
							<div class="up-item">
								{% if request.user.is_authenticated %}
								<i>{{ user.username }} | <a href="{% url 'logout' %}">Выйти</a></i>
								{% else %}
								<a href="{% url 'login' %}">Войти</a> или <a href="{% url 'register' %}">Зарегистрироваться</a>
								{% endif %}
							</div>
							<div class="up-item">
								<div class="shopping-card">
									<i class="flaticon-bag"></i>
									<span>0</span>
								</div>
								<a href="{% url 'cart:cart_detail' %}">Корзина</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<nav class="main-navbar">
			<div class="container">
				<ul class="main-menu">
					<li><a href="{% url 'index' %}">БРЕНДЫ</a>
						<ul class="sub-menu">
							<li><a href="{% url 'alexandermcqueen' %}">AlexanderMcQueen</a></li>
							<li><a href="{% url 'balenciaga' %}">Balenciaga</a></li>
							<li><a href="{% url 'moncler' %}">Moncler</a></li>
							<li><a href="{% url 'offwhite' %}">Off-White</a></li>
							<li><a href="{% url 'valentino' %}">Valentino</a></li>
						</ul>
					</li>
					<li><a href="{% url 'productmen' %}">МУЖСКОЕ</a></li>
					<li><a href="{% url 'productwomen' %}">ЖЕНСКОЕ</a></li>
					<li><a href="#">КРОССОВКИ</a>
						<ul class="sub-menu">
							<li><a href="{% url 'productsneakersformen' %}">МУЖСКИЕ</a></li>
							<li><a href="{% url 'productsneakersforwomen' %}">ЖЕНСКИЕ</a></li>
						</ul>
					</li>
					<li><a href="#">ЧАСЫ</a>
						<ul class="sub-menu">
							<li><a href="{% url 'chopard' %}">Chopard</a></li>
							<li><a href="{% url 'degrisogono' %}">de GRISOGONO</a></li>
							<li><a href="{% url 'girardperregaux' %}">Girard-Perregaux</a></li>
							<li><a href="{% url 'hublot' %}">Hublot</a></li>
							<li><a href="{% url 'breitling' %}">Breitling</a></li>
							<li><a href="{% url 'tagheuer' %}">TAG Heuer</a></li>
							<li><a href="{% url 'tudor' %}">Tudor</a></li>
							<li><a href="{% url 'chanel' %}">Chanel</a></li>
						</ul>
					</li>
					<li><a href="#">УКРАШЕНИЯ<span class="new">New</span></a>
						<ul class="sub-menu">
							<li><a href="{% url 'productjewerlyformen' %}">МУЖСКОЕ</a></li>
							<li><a href="{% url 'productjewerlyforwomen' %}">ЖЕНСКОЕ</a></li>
						</ul>
					</li>


					<li><a href="#">СТРАНИЦЫ</a>
						<ul class="sub-menu">
							<li><a href="{% url 'product' %}">Товары</a></li>
							<li><a href="{% url 'category' %}">Категории</a></li>
							<li><a href="{% url 'cart:cart_detail' %}">Корзина</a></li>
							<li><a href="{% url 'checkout' %}">Проверка</a></li>
							<li><a href="{% url 'contact' %}">Контакты</a></li>
						</ul>
					</li>
					<li><a href="{% url 'news' %}">НОВОСТИ</a></li>
				</ul>
			</div>
		</nav>
	</header>
	<!-- Header section end -->


	<!-- Page info -->
	<div class="page-top-info">
		<div class="container">
			<h4>Ваша корзина</h4>
			<div class="site-pagination">
				<a href="{% url 'index' %}">Домой</a> /
				<a href="{% url 'category' %}">Категории</a>
			</div>
		</div>
	</div>
	<!-- Page info end -->


	<!-- product section -->
{% block content %}
<table class="cart">
	{% if cart %}
    <thead>
    <tr>
		<th></th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Очистить</th>
        <th>Цена за штуку</th>
        <th>Цена</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{product.get_absolute_url}}">
                <img src="{% if product.photo_product %}{{product.photo_product.url}}{% endif %}">
            </a>
        </td>
        <td>{{product.title}}</td>
        <td>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{item.update_quantity_form.quantity}}
                {{item.update_quantity_form.update}}
                <input type="submit" value="Обновить">
                {% csrf_token %}
            </form>
        </td>
        <td><a href="{% url 'cart:cart_remove' product.id %}">Очистить</a></td>
        <td class="num">${{item.price}}</td>
        <td class="num">${{item.total_price}}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Итоговая стоимость</td>
        <td colspan="4"></td>
        <td class="num">${{cart.get_total_price}}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'index' %}" class="button light">Продолжить покупки</a>
    <a href="#" class="button">Оформить</a>
</p>
	{% else %}

	<h2 class="test-right">Корзина пустая</h2>
	<p class="text-right">
	<a href="{% url 'index' %}" class="button light">Продолжить покупки</a>
	</p>
	{% endif %}
{% endblock %}
	<!-- product section end -->


	<!-- Footer section -->
	<section class="footer-section">
		<div class="container">
			<div class="footer-logo text-center">
				<a href="index.html"><img src="{% static 'shop/./images/logo-light.png' %}" alt=""></a>
			</div>
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget about-widget">
						<h2>About</h2>
						<p>INFINITY-это один из крупнейших интернет магазинов товаров, который уже более 4 лет обеспечивает товарами более миллиона человек по всему миру. В 2021 году было принято решение доставлять наши товары по всему миру, и сегодня каждый может по достоинству оценить наш товар.</p>
						<img src="{% static 'shop/images/cards.png' %}" alt="">
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget about-widget">
						<h2>Questions</h2>
						<ul>
							<li><a href="">О нас</a></li>
							<li><a href="">Отслеживать заказы</a></li>
							<li><a href="">Возврат</a></li>
							<li><a href="">Работа</a></li>
							<li><a href="">Доставка</a></li>
						</ul>
						<ul>
							<li><a href="">Партнеры</a></li>
							<li><a href="">Поддержка</a></li>
							<li><a href="">Условия пользования</a></li>
							<li><a href="">Блог</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget contact-widget">
						<h2>Questions</h2>
						<div class="con-info">
							<span>C.</span>
							<p>INFT</p>
						</div>
						<div class="con-info">
							<span>B.</span>
							<p>Krasnodar city, 52 komarova Street</p>
						</div>
						<div class="con-info">
							<span>T.</span>
							<p>+79884527482</p>
						</div>
						<div class="con-info">
							<span>E.</span>
							<p>Infinity@gmail.com</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="social-links-warp">
			<div class="container">
				<div class="social-links">
					<a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
					<a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
					<a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
					<a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
				</div>

<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
<p class="text-white text-center mt-5">Copyright &copy;2021 All rights reserved</p>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

			</div>
		</div>
	</section>
	<!-- Footer section end -->



	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'shop/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'shop/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'shop/js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'shop/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'shop/js/jquery.nicescroll.min.js' %}"></script>
	<script src="{% static 'shop/js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'shop/js/jquery-ui.min.js' %}"></script>
	<script src="{% static 'shop/js/main.js' %}"></script>

	</body>
</html>